---
name: Cloudfy9 Packer GitHub Actions
author: "cloudfy9"
description: This GitHub action is used to perform action linting.

inputs:
  files:
    description: this input contains the individual files you want to scan
    required: false
  arguments:
    description: this input contains additional arguments to pass to command
    required: false
  format:
    description: this input contains the output format. Supported formats are json or markdown
    required: false
    default: "'{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}'"

outputs:
  command:
    description: interpolated command including arguments will be executed

runs:
  using: 'composite'
  steps:
    - name: Install Action Linter Binary
      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      shell: bash

    - name: Check Workflow Files
      run: ${{ steps.get_actionlint.outputs.executable }} ${{ inputs.arguments }} -format ${{ inputs.format }} ${{ inputs.files }}
      shell: bash

branding:
  color: green
  icon: terminal
